default: &default
  adapter: postgresql
  encoding: UTF8
  pool: 5

development:
  adapter: postgresql
  encoding: UTF8
  database: lib_dev
  username: agnivesh
  password: qweras

test:
  adapter: postgresql
  encoding: UTF8
  database: lib_test
  username: agnivesh
  password: qweras

production:
  adapter: postgresql
  encoding: UTF8
  database: lib_pro
  username: agnivesh
  password: qweras